apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: keyval-operator-system
  labels:
    app.kubernetes.io/name: keyval-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: controller-manager
      imagePullSecrets:
        - name: registry-local
      containers:
      - name: manager
        image: controller:latest
        imagePullPolicy: Always
        envFrom:
        - configMapRef:
            name: keyval-operator-config
        args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=:8080
        - --leader-elect
        ports:
        - name: metrics
          containerPort: 8080
        - name: health
          containerPort: 8081
        livenessProbe:
          httpGet:
            path: /healthz
            port: health
        readinessProbe:
          httpGet:
            path: /readyz
            port: health
