apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keyval-operator-manager-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "patch", "delete"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch", "create", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch", "update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "patch", "update", "delete"]
  # Allow rolling update path to evict pods via policy/v1 Eviction subresource
- apiGroups: [""]
  resources: ["pods/eviction"]
  verbs: ["create"]
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["policy"]
  resources: ["poddisruptionbudgets"]
  verbs: ["get", "list", "watch", "create", "patch", "delete"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]
- apiGroups: ["keyval.ivelok.io"]
  resources: ["keyvalclusters"]
  verbs: ["get", "list", "watch", "patch", "update"]
- apiGroups: ["keyval.ivelok.io"]
  resources: ["keyvalclusters/status"]
  verbs: ["get", "patch", "update"]
- apiGroups: ["keyval.ivelok.io"]
  resources: ["keyvalclusters/finalizers"]
  verbs: ["get", "update", "patch"]
